# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\Documents\NEA menus\RenewBookingMenu.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(938, 821)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.Frame1 = QtWidgets.QFrame(self.centralwidget)
        self.Frame1.setGeometry(QtCore.QRect(0, 0, 71, 841))
        self.Frame1.setStyleSheet("background-color: rgb(36, 37, 37, 252);")
        self.Frame1.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame1.setObjectName("Frame1")
        self.BackButton = QtWidgets.QPushButton(self.Frame1)
        self.BackButton.setGeometry(QtCore.QRect(10, 10, 41, 41))
        self.BackButton.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.864, y1:0.892045, x2:0.124591, y2:0.165, stop:0 rgba(0, 104, 113, 255), stop:1 rgba(7, 7, 9, 210));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 10px;\n"
"border-color: rgb(135, 135, 135);\n"
"border-radius: 10px;\n"
"")
        self.BackButton.setObjectName("BackButton")
        self.Frame1_2 = QtWidgets.QFrame(self.centralwidget)
        self.Frame1_2.setGeometry(QtCore.QRect(70, 0, 871, 71))
        self.Frame1_2.setStyleSheet("background-color: rgb(36, 37, 37, 252);")
        self.Frame1_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.Frame1_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Frame1_2.setObjectName("Frame1_2")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(50, 60, 891, 761))
        self.frame.setStyleSheet("border-width: 3px;\n"
"background-color: rgb(26, 26, 26);\n"
"border-radius: 10px;\n"
"")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.textBrowser = QtWidgets.QTextBrowser(self.frame)
        self.textBrowser.setGeometry(QtCore.QRect(10, 10, 621, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(48)
        self.textBrowser.setFont(font)
        self.textBrowser.setStyleSheet("color: rgb(237, 237, 237);\n"
"background-color: qlineargradient(spread:pad, x1:0.12, y1:0.489, x2:1, y2:0.517, stop:0.210227 rgba(0, 104, 113, 194), stop:1 rgba(23, 25, 23, 158));")
        self.textBrowser.setObjectName("textBrowser")
        self.roomnumlabel = QtWidgets.QLabel(self.frame)
        self.roomnumlabel.setGeometry(QtCore.QRect(10, 320, 211, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        self.roomnumlabel.setFont(font)
        self.roomnumlabel.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.roomnumlabel.setObjectName("roomnumlabel")
        self.Namelabel = QtWidgets.QLabel(self.frame)
        self.Namelabel.setGeometry(QtCore.QRect(10, 240, 431, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        self.Namelabel.setFont(font)
        self.Namelabel.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.Namelabel.setObjectName("Namelabel")
        self.nameentry = QtWidgets.QTextEdit(self.frame)
        self.nameentry.setGeometry(QtCore.QRect(190, 250, 241, 41))
        self.nameentry.setStyleSheet("background-color: rgb(36, 37, 37, 252);\n"
"selection-color: rgb(4, 138, 140);\n"
"selection-background-color: rgb(181, 181, 181);\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.nameentry.setObjectName("nameentry")
        self.roomnumbox = QtWidgets.QSpinBox(self.frame)
        self.roomnumbox.setGeometry(QtCore.QRect(150, 330, 61, 41))
        self.roomnumbox.setStyleSheet("background-color: rgb(36, 37, 37, 252);\n"
"selection-color: rgb(4, 138, 140);\n"
"selection-background-color: rgb(181, 181, 181);\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.roomnumbox.setObjectName("roomnumbox")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(10, 120, 461, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.label.setObjectName("label")
        self.confirmbutton = QtWidgets.QPushButton(self.frame)
        self.confirmbutton.setGeometry(QtCore.QRect(250, 650, 341, 81))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(18)
        self.confirmbutton.setFont(font)
        self.confirmbutton.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.confirmbutton.setObjectName("confirmbutton")
        self.errorlabel = QtWidgets.QLabel(self.frame)
        self.errorlabel.setGeometry(QtCore.QRect(270, 580, 311, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.errorlabel.setFont(font)
        self.errorlabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.501, y1:0.897727, x2:0.528, y2:0, stop:0 rgba(140, 171, 174, 255), stop:1 rgba(225, 225, 219, 255));\n"
"color: rgb(176, 0, 0);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.errorlabel.setObjectName("errorlabel")
        self.successlabel = QtWidgets.QLabel(self.frame)
        self.successlabel.setGeometry(QtCore.QRect(240, 470, 371, 101))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(12)
        self.successlabel.setFont(font)
        self.successlabel.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.501, y1:0.897727, x2:0.528, y2:0, stop:0 rgba(140, 171, 174, 255), stop:1 rgba(225, 225, 219, 255));\n"
"color: rgb(176, 0, 0);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.successlabel.setObjectName("successlabel")
        self.nightslabel = QtWidgets.QLabel(self.frame)
        self.nightslabel.setGeometry(QtCore.QRect(10, 390, 251, 61))
        font = QtGui.QFont()
        font.setFamily("Segoe UI Light")
        font.setPointSize(14)
        self.nightslabel.setFont(font)
        self.nightslabel.setStyleSheet("background-color:qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.nightslabel.setObjectName("nightslabel")
        self.nightsbox = QtWidgets.QSpinBox(self.frame)
        self.nightsbox.setGeometry(QtCore.QRect(190, 400, 61, 41))
        self.nightsbox.setStyleSheet("background-color: rgb(36, 37, 37, 252);\n"
"selection-color: rgb(4, 138, 140);\n"
"selection-background-color: rgb(181, 181, 181);\n"
"alternate-background-color: qlineargradient(spread:pad, x1:0.949, y1:0.102273, x2:0.42, y2:0.391636, stop:0 rgba(16, 137, 135, 255), stop:1 rgba(36, 37, 37, 252));\n"
"color: rgb(215, 219, 218);\n"
"border-width: 3px;\n"
"border-color: rgb(61, 61, 61);\n"
"border-radius: 10px;")
        self.nightsbox.setObjectName("nightsbox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.BackButton.setText(_translate("MainWindow", "Back"))
        self.textBrowser.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Segoe UI Light\'; font-size:48pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Renew Booking:</p></body></html>"))
        self.roomnumlabel.setText(_translate("MainWindow", "Room number:"))
        self.Namelabel.setText(_translate("MainWindow", "Name under booking:"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Please enter the details of your existing booking below:</p></body></html>"))
        self.confirmbutton.setText(_translate("MainWindow", "Confirm renewal"))
        self.errorlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">No bookings found matching entered details</p></body></html>"))
        self.successlabel.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:22pt;\">Booking extended successfully</span></p></body></html>"))
        self.nightslabel.setText(_translate("MainWindow", "Nights to extend by:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
